runtime: python39
entrypoint: gunicorn -b :$PORT app:app

# env_variables:
#   SECRET_KEY: "3b1215270a97382f9472e9a871ab01c0"
#   DATABASE_URL: "your-database-url"
#   GOOGLE_APPLICATION_CREDENTIALS: "/Users/jackzhang/Desktop/DesktopProject/devcomponent-vaulted-scholar-422700-m6-cd0cf5e09b00.json"

# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 1
#   max_instances: 10

# resources:
#   cpu: 1
#   memory_gb: 1
#   disk_size_gb: 10
