runtime: nodejs16.15.0
# env: flex

# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 1
#   max_instances: 10

# resources:
#   cpu: 1
#   memory_gb: 1
#   disk_size_gb: 10

entrypoint: npm run build
